[package]
name = "easy_private_voting_contract"
type = "contract"
authors = [ "" ]
compiler_version = ">=1.0.0"

[dependencies]
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.85.0", directory = "noir-projects/aztec-nr/authwit" }
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v0.85.0", directory = "noir-projects/aztec-nr/aztec" }
jwt = { tag = "v0.5.0", git = "https://github.com/zkemail/noir-jwt" }